# Generated by Django 5.2.9 on 2025-12-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('categoria', models.CharField(choices=[('frutas', 'Frutas'), ('verduras', 'Verduras'), ('otros', 'Otros')], max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad', models.CharField(default='UNIDAD', max_length=50)),
                ('descuento_activo', models.BooleanField(default=False)),
                ('porcentaje_descuento', models.IntegerField(default=0)),
            ],
        ),
    ]
