# Generated by Django 5.2.9 on 2025-12-02 20:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['-id'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AddField(
            model_name='producto',
            name='actualizado',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('frutas', 'Frutas'), ('verduras', 'Verduras'), ('otros', 'Otros')], max_length=20, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descuento_activo',
            field=models.BooleanField(default=False, verbose_name='¿Activar descuento?'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(upload_to='productos/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='porcentaje_descuento',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje de descuento'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad',
            field=models.CharField(choices=[('kg', 'Kilogramo (kg)'), ('unidad', 'Unidad'), ('paquete', 'Paquete')], default='unidad', max_length=20, verbose_name='Unidad de medida'),
        ),
    ]
